### ISSUE TITLE
Simulate affect of TVL increase on APY in sensei strategies

### ISSUE THREAD

**Issue by akiraonstarknet** [strkfarm/strategy-analysis#10]
Sensei strategies deposit and borrow from zklend and nostra. Use the current supply and borrow TVL of these protocols along with APY formula of them to understand the affects of deposits into sensei strategy on net apy 

Output: 
For each of the strategies, plot deposit (usd) vs apy plot. Meaning how does apy change as u increase deposit. The deposit range is from 10k usd to 10M.

Also plot the individual deposit and borrow ApYs of the pools involved for each of the protocols  against deposit usd.

**Comment by ManvithaMolakala** [comment]
I would like to work on this.
