### ISSUE TITLE
Create dashboards on Dune

### ISSUE THREAD

**Issue by akiraonstarknet** [strkfarm/strategy-analysis#13]
Hi, we want dune dashboards to show our activity. For each of the strategies, please have the following charts:

1. Historical day wise TVL ($ and token terms)
2. Token inflows and outflows (weekly) - inflows to be shown above x axis, outflows below x axis
3. Rebalances - Show the weekly number of rebalances done
4. Harvests - Show the amount of strk harvested each week and amount of underlying token deposited
5. Share price/LP token price plot daily

**Comment by ManvithaMolakala** [comment]
I want to work on this issue.

**Comment by estherbreath** [comment]
@akiraonstarknet 
I am a full stack developer with seasoned knowledge in smart contract development, and would like to work on this issue

**Comment by ManvithaMolakala** [comment]
Closes issue #13

Hi

I have worked on this issue. Please find it in the [dune dashboard](https://dune.com/manvitha/strkfarm). 

<img width="930" alt="2" src="https://github.com/user-attachments/assets/50668db7-d512-496c-abf8-0930a8de8e78">

Please let me know if any changes are required.

**Comment by akiraonstarknet** [comment]
Thanks @ManvithaMolakala. This looks great.
