### ISSUE TITLE
Dune dashboard for endur

### ISSUE THREAD

**Issue by akiraonstarknet** [strkfarm/strategy-analysis#16]
1. Day wise TVL of Endur in STRK and USD terms
2. Current snapshot of STRK held in delegator pools
3. Daily withdraw queue vs claimed withdrawals

**Comment by ManvithaMolakala** [comment]
I want to work on this.

**Comment by ManvithaMolakala** [comment]
Hi @akiraonstarknet 
I have made the dashboard. Please let me know if any changes are required. 

[Dashboard](https://dune.com/manvitha/endur-lst-analytics)
